class DotPrison::Prison::Finance < DotPrison::StoreConsumer
  handle(:balance, :Float64, :Balance)
  handle(:last_day, :Int32, :LastDay)
  handle(:last_hour, :Int32, :LastHour)
  handle(:sale_price, :Int32, :SalePrice)
  handle(:bank_loan, :Int32, :BankLoan)
  handle(:bank_credit_rating, :Float64, :BankCreditRating)
  handle(:ownership, :Int32, :Ownership)
  handle(:wardens_cut, :Float64, :WardensCut)
  handle(:staff_pay_modifier, :Float64, :StaffPayModifier)
  handle(:daily_exports, :Float64, :DailyExports)
  handle(:daily_exports_yesterday, :Int32, :DailyExportsYesterday)
  handle(:daily_shop_revenue, :Float64, :DailyShopRevenue)
  handle(:daily_shop_revenue_yesterday, :Int32, :DailyShopRevenueYesterday)
  handle(:daily_prisoner_wages, :Float64, :DailyPrisonerWages)
  handle(:daily_prisoner_wages_yesterday, :Int32, :DailyPrisonerWagesYesterday)
  handle(:daily_staff_food, :Float64, :DailyStaffFood)
  handle(:daily_staff_food_yesterday, :Int32, :DailyStaffFoodYesterday)
end
